language: ruby
rvm:
- 1.29.3
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rspec
services:
- postgresql
- redis-server
notifications:
  email: false
