
language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler -v 1.15.1
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
notifications:
    - false
scripts:
  - bundle exec rspec spec
after_script:
  - bundle exec rake coveralls:push
